name: Hanoi Towers E2E

on:
  push:
    branches:
      - main

jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Cypress run
        uses: cypress-io/github-action@v6