name: Hanoi Towers E2E

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'

jobs:
  smoke-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment: ["production", "staging"]
    env:
      CYPRESS_ENVIRONMENT_NAME: ${{ matrix.environment }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Cypress run
        uses: cypress-io/github-action@v6
      - name: Upload videos as artifacts
        uses: actions/upload-artifact@v4
        with:
          name: cypress-videos-${{ matrix.environment }}
          path: cypress/videos
